-- Auto-generated from fixtures-2026.md. Idempotent: re-runnable.
-- Run AFTER schema.sql and seed.sql.
-- All kickoff times are ET (EDT, UTC-4 during June/July) converted to UTC.
-- R32/R16/QF/SF times default to 12:00 ET (just to anchor the date); refine in Admin.

begin;

-- ===== Group matches =====
update public.matches set kickoff = '2026-06-11T19:00:00Z', venue = 'Estadio Azteca, Mexico City' where stage = 'group' and group_letter = 'A' and ((home_team_id = (select id from public.teams where code='MEX') and away_team_id = (select id from public.teams where code='RSA')) or (home_team_id = (select id from public.teams where code='RSA') and away_team_id = (select id from public.teams where code='MEX')));
update public.matches set kickoff = '2026-06-12T02:00:00Z', venue = 'Estadio Akron, Guadalajara' where stage = 'group' and group_letter = 'A' and ((home_team_id = (select id from public.teams where code='KOR') and away_team_id = (select id from public.teams where code='CZE')) or (home_team_id = (select id from public.teams where code='CZE') and away_team_id = (select id from public.teams where code='KOR')));
update public.matches set kickoff = '2026-06-12T19:00:00Z', venue = 'BMO Field, Toronto' where stage = 'group' and group_letter = 'B' and ((home_team_id = (select id from public.teams where code='CAN') and away_team_id = (select id from public.teams where code='BIH')) or (home_team_id = (select id from public.teams where code='BIH') and away_team_id = (select id from public.teams where code='CAN')));
update public.matches set kickoff = '2026-06-13T01:00:00Z', venue = 'SoFi Stadium, Los Angeles' where stage = 'group' and group_letter = 'D' and ((home_team_id = (select id from public.teams where code='USA') and away_team_id = (select id from public.teams where code='PAR')) or (home_team_id = (select id from public.teams where code='PAR') and away_team_id = (select id from public.teams where code='USA')));
update public.matches set kickoff = '2026-06-13T19:00:00Z', venue = 'MetLife Stadium, New York/NJ' where stage = 'group' and group_letter = 'C' and ((home_team_id = (select id from public.teams where code='BRA') and away_team_id = (select id from public.teams where code='MAR')) or (home_team_id = (select id from public.teams where code='MAR') and away_team_id = (select id from public.teams where code='BRA')));
update public.matches set kickoff = '2026-06-13T19:00:00Z', venue = 'Levi''s Stadium, San Francisco Bay Area' where stage = 'group' and group_letter = 'B' and ((home_team_id = (select id from public.teams where code='QAT') and away_team_id = (select id from public.teams where code='SUI')) or (home_team_id = (select id from public.teams where code='SUI') and away_team_id = (select id from public.teams where code='QAT')));
update public.matches set kickoff = '2026-06-14T01:00:00Z', venue = 'Gillette Stadium, Boston' where stage = 'group' and group_letter = 'C' and ((home_team_id = (select id from public.teams where code='HAI') and away_team_id = (select id from public.teams where code='SCO')) or (home_team_id = (select id from public.teams where code='SCO') and away_team_id = (select id from public.teams where code='HAI')));
update public.matches set kickoff = '2026-06-14T01:00:00Z', venue = 'BC Place, Vancouver' where stage = 'group' and group_letter = 'D' and ((home_team_id = (select id from public.teams where code='AUS') and away_team_id = (select id from public.teams where code='TUR')) or (home_team_id = (select id from public.teams where code='TUR') and away_team_id = (select id from public.teams where code='AUS')));
update public.matches set kickoff = '2026-06-14T17:00:00Z', venue = 'NRG Stadium, Houston' where stage = 'group' and group_letter = 'E' and ((home_team_id = (select id from public.teams where code='GER') and away_team_id = (select id from public.teams where code='CUW')) or (home_team_id = (select id from public.teams where code='CUW') and away_team_id = (select id from public.teams where code='GER')));
update public.matches set kickoff = '2026-06-14T18:00:00Z', venue = 'Lincoln Financial Field, Philadelphia' where stage = 'group' and group_letter = 'E' and ((home_team_id = (select id from public.teams where code='CIV') and away_team_id = (select id from public.teams where code='ECU')) or (home_team_id = (select id from public.teams where code='ECU') and away_team_id = (select id from public.teams where code='CIV')));
update public.matches set kickoff = '2026-06-14T20:00:00Z', venue = 'AT&T Stadium, Dallas' where stage = 'group' and group_letter = 'F' and ((home_team_id = (select id from public.teams where code='NED') and away_team_id = (select id from public.teams where code='JPN')) or (home_team_id = (select id from public.teams where code='JPN') and away_team_id = (select id from public.teams where code='NED')));
update public.matches set kickoff = '2026-06-14T21:00:00Z', venue = 'Estadio BBVA, Monterrey' where stage = 'group' and group_letter = 'F' and ((home_team_id = (select id from public.teams where code='SWE') and away_team_id = (select id from public.teams where code='TUN')) or (home_team_id = (select id from public.teams where code='TUN') and away_team_id = (select id from public.teams where code='SWE')));
update public.matches set kickoff = '2026-06-15T16:00:00Z', venue = 'Mercedes-Benz Stadium, Atlanta' where stage = 'group' and group_letter = 'H' and ((home_team_id = (select id from public.teams where code='ESP') and away_team_id = (select id from public.teams where code='CPV')) or (home_team_id = (select id from public.teams where code='CPV') and away_team_id = (select id from public.teams where code='ESP')));
update public.matches set kickoff = '2026-06-15T17:00:00Z', venue = 'Hard Rock Stadium, Miami' where stage = 'group' and group_letter = 'H' and ((home_team_id = (select id from public.teams where code='KSA') and away_team_id = (select id from public.teams where code='URU')) or (home_team_id = (select id from public.teams where code='URU') and away_team_id = (select id from public.teams where code='KSA')));
update public.matches set kickoff = '2026-06-15T19:00:00Z', venue = 'Lumen Field, Seattle' where stage = 'group' and group_letter = 'G' and ((home_team_id = (select id from public.teams where code='BEL') and away_team_id = (select id from public.teams where code='EGY')) or (home_team_id = (select id from public.teams where code='EGY') and away_team_id = (select id from public.teams where code='BEL')));
update public.matches set kickoff = '2026-06-15T20:00:00Z', venue = 'SoFi Stadium, Los Angeles' where stage = 'group' and group_letter = 'G' and ((home_team_id = (select id from public.teams where code='IRN') and away_team_id = (select id from public.teams where code='NZL')) or (home_team_id = (select id from public.teams where code='NZL') and away_team_id = (select id from public.teams where code='IRN')));
update public.matches set kickoff = '2026-06-16T14:00:00Z', venue = 'MetLife Stadium, New York/NJ' where stage = 'group' and group_letter = 'I' and ((home_team_id = (select id from public.teams where code='FRA') and away_team_id = (select id from public.teams where code='SEN')) or (home_team_id = (select id from public.teams where code='SEN') and away_team_id = (select id from public.teams where code='FRA')));
update public.matches set kickoff = '2026-06-16T17:00:00Z', venue = 'Gillette Stadium, Boston' where stage = 'group' and group_letter = 'I' and ((home_team_id = (select id from public.teams where code='IRQ') and away_team_id = (select id from public.teams where code='NOR')) or (home_team_id = (select id from public.teams where code='NOR') and away_team_id = (select id from public.teams where code='IRQ')));
update public.matches set kickoff = '2026-06-16T20:00:00Z', venue = 'Arrowhead Stadium, Kansas City' where stage = 'group' and group_letter = 'J' and ((home_team_id = (select id from public.teams where code='ARG') and away_team_id = (select id from public.teams where code='ALG')) or (home_team_id = (select id from public.teams where code='ALG') and away_team_id = (select id from public.teams where code='ARG')));
update public.matches set kickoff = '2026-06-16T23:00:00Z', venue = 'Levi''s Stadium, San Francisco Bay Area' where stage = 'group' and group_letter = 'J' and ((home_team_id = (select id from public.teams where code='AUT') and away_team_id = (select id from public.teams where code='JOR')) or (home_team_id = (select id from public.teams where code='JOR') and away_team_id = (select id from public.teams where code='AUT')));
update public.matches set kickoff = '2026-06-17T12:00:00Z', venue = 'NRG Stadium, Houston' where stage = 'group' and group_letter = 'K' and ((home_team_id = (select id from public.teams where code='POR') and away_team_id = (select id from public.teams where code='COD')) or (home_team_id = (select id from public.teams where code='COD') and away_team_id = (select id from public.teams where code='POR')));
update public.matches set kickoff = '2026-06-17T20:00:00Z', venue = 'AT&T Stadium, Dallas' where stage = 'group' and group_letter = 'L' and ((home_team_id = (select id from public.teams where code='ENG') and away_team_id = (select id from public.teams where code='CRO')) or (home_team_id = (select id from public.teams where code='CRO') and away_team_id = (select id from public.teams where code='ENG')));
update public.matches set kickoff = '2026-06-17T18:00:00Z', venue = 'BMO Field, Toronto' where stage = 'group' and group_letter = 'L' and ((home_team_id = (select id from public.teams where code='GHA') and away_team_id = (select id from public.teams where code='PAN')) or (home_team_id = (select id from public.teams where code='PAN') and away_team_id = (select id from public.teams where code='GHA')));
update public.matches set kickoff = '2026-06-17T21:00:00Z', venue = 'Estadio Azteca, Mexico City' where stage = 'group' and group_letter = 'K' and ((home_team_id = (select id from public.teams where code='UZB') and away_team_id = (select id from public.teams where code='COL')) or (home_team_id = (select id from public.teams where code='COL') and away_team_id = (select id from public.teams where code='UZB')));
update public.matches set kickoff = '2026-06-18T16:00:00Z', venue = 'Mercedes-Benz Stadium, Atlanta' where stage = 'group' and group_letter = 'A' and ((home_team_id = (select id from public.teams where code='RSA') and away_team_id = (select id from public.teams where code='KOR')) or (home_team_id = (select id from public.teams where code='KOR') and away_team_id = (select id from public.teams where code='RSA')));
update public.matches set kickoff = '2026-06-18T23:00:00Z', venue = 'Estadio Azteca, Mexico City' where stage = 'group' and group_letter = 'A' and ((home_team_id = (select id from public.teams where code='CZE') and away_team_id = (select id from public.teams where code='MEX')) or (home_team_id = (select id from public.teams where code='MEX') and away_team_id = (select id from public.teams where code='CZE')));
update public.matches set kickoff = '2026-06-18T19:00:00Z', venue = 'BC Place, Vancouver' where stage = 'group' and group_letter = 'B' and ((home_team_id = (select id from public.teams where code='BIH') and away_team_id = (select id from public.teams where code='SUI')) or (home_team_id = (select id from public.teams where code='SUI') and away_team_id = (select id from public.teams where code='BIH')));
update public.matches set kickoff = '2026-06-18T22:00:00Z', venue = 'BMO Field, Toronto' where stage = 'group' and group_letter = 'B' and ((home_team_id = (select id from public.teams where code='QAT') and away_team_id = (select id from public.teams where code='CAN')) or (home_team_id = (select id from public.teams where code='CAN') and away_team_id = (select id from public.teams where code='QAT')));
update public.matches set kickoff = '2026-06-19T16:00:00Z', venue = 'Lincoln Financial Field, Philadelphia' where stage = 'group' and group_letter = 'C' and ((home_team_id = (select id from public.teams where code='MAR') and away_team_id = (select id from public.teams where code='SCO')) or (home_team_id = (select id from public.teams where code='SCO') and away_team_id = (select id from public.teams where code='MAR')));
update public.matches set kickoff = '2026-06-19T19:00:00Z', venue = 'Gillette Stadium, Boston' where stage = 'group' and group_letter = 'C' and ((home_team_id = (select id from public.teams where code='BRA') and away_team_id = (select id from public.teams where code='HAI')) or (home_team_id = (select id from public.teams where code='HAI') and away_team_id = (select id from public.teams where code='BRA')));
update public.matches set kickoff = '2026-06-19T22:00:00Z', venue = 'Estadio BBVA, Monterrey' where stage = 'group' and group_letter = 'D' and ((home_team_id = (select id from public.teams where code='PAR') and away_team_id = (select id from public.teams where code='TUR')) or (home_team_id = (select id from public.teams where code='TUR') and away_team_id = (select id from public.teams where code='PAR')));
update public.matches set kickoff = '2026-06-20T01:00:00Z', venue = 'Lumen Field, Seattle' where stage = 'group' and group_letter = 'D' and ((home_team_id = (select id from public.teams where code='USA') and away_team_id = (select id from public.teams where code='AUS')) or (home_team_id = (select id from public.teams where code='AUS') and away_team_id = (select id from public.teams where code='USA')));
update public.matches set kickoff = '2026-06-20T16:00:00Z', venue = 'Arrowhead Stadium, Kansas City' where stage = 'group' and group_letter = 'E' and ((home_team_id = (select id from public.teams where code='CUW') and away_team_id = (select id from public.teams where code='ECU')) or (home_team_id = (select id from public.teams where code='ECU') and away_team_id = (select id from public.teams where code='CUW')));
update public.matches set kickoff = '2026-06-20T19:00:00Z', venue = 'AT&T Stadium, Dallas' where stage = 'group' and group_letter = 'E' and ((home_team_id = (select id from public.teams where code='GER') and away_team_id = (select id from public.teams where code='CIV')) or (home_team_id = (select id from public.teams where code='CIV') and away_team_id = (select id from public.teams where code='GER')));
update public.matches set kickoff = '2026-06-20T22:00:00Z', venue = 'NRG Stadium, Houston' where stage = 'group' and group_letter = 'F' and ((home_team_id = (select id from public.teams where code='JPN') and away_team_id = (select id from public.teams where code='TUN')) or (home_team_id = (select id from public.teams where code='TUN') and away_team_id = (select id from public.teams where code='JPN')));
update public.matches set kickoff = '2026-06-21T01:00:00Z', venue = 'Arrowhead Stadium, Kansas City' where stage = 'group' and group_letter = 'F' and ((home_team_id = (select id from public.teams where code='NED') and away_team_id = (select id from public.teams where code='SWE')) or (home_team_id = (select id from public.teams where code='SWE') and away_team_id = (select id from public.teams where code='NED')));
update public.matches set kickoff = '2026-06-21T16:00:00Z', venue = 'SoFi Stadium, Los Angeles' where stage = 'group' and group_letter = 'G' and ((home_team_id = (select id from public.teams where code='EGY') and away_team_id = (select id from public.teams where code='NZL')) or (home_team_id = (select id from public.teams where code='NZL') and away_team_id = (select id from public.teams where code='EGY')));
update public.matches set kickoff = '2026-06-21T19:00:00Z', venue = 'Lumen Field, Seattle' where stage = 'group' and group_letter = 'G' and ((home_team_id = (select id from public.teams where code='BEL') and away_team_id = (select id from public.teams where code='IRN')) or (home_team_id = (select id from public.teams where code='IRN') and away_team_id = (select id from public.teams where code='BEL')));
update public.matches set kickoff = '2026-06-21T22:00:00Z', venue = 'Hard Rock Stadium, Miami' where stage = 'group' and group_letter = 'H' and ((home_team_id = (select id from public.teams where code='CPV') and away_team_id = (select id from public.teams where code='URU')) or (home_team_id = (select id from public.teams where code='URU') and away_team_id = (select id from public.teams where code='CPV')));
update public.matches set kickoff = '2026-06-22T01:00:00Z', venue = 'Mercedes-Benz Stadium, Atlanta' where stage = 'group' and group_letter = 'H' and ((home_team_id = (select id from public.teams where code='ESP') and away_team_id = (select id from public.teams where code='KSA')) or (home_team_id = (select id from public.teams where code='KSA') and away_team_id = (select id from public.teams where code='ESP')));
update public.matches set kickoff = '2026-06-22T16:00:00Z', venue = 'Lincoln Financial Field, Philadelphia' where stage = 'group' and group_letter = 'I' and ((home_team_id = (select id from public.teams where code='NOR') and away_team_id = (select id from public.teams where code='SEN')) or (home_team_id = (select id from public.teams where code='SEN') and away_team_id = (select id from public.teams where code='NOR')));
update public.matches set kickoff = '2026-06-22T19:00:00Z', venue = 'MetLife Stadium, New York/NJ' where stage = 'group' and group_letter = 'I' and ((home_team_id = (select id from public.teams where code='FRA') and away_team_id = (select id from public.teams where code='IRQ')) or (home_team_id = (select id from public.teams where code='IRQ') and away_team_id = (select id from public.teams where code='FRA')));
update public.matches set kickoff = '2026-06-22T19:00:00Z', venue = 'SoFi Stadium, Los Angeles' where stage = 'group' and group_letter = 'J' and ((home_team_id = (select id from public.teams where code='ALG') and away_team_id = (select id from public.teams where code='AUT')) or (home_team_id = (select id from public.teams where code='AUT') and away_team_id = (select id from public.teams where code='ALG')));
update public.matches set kickoff = '2026-06-22T22:00:00Z', venue = 'Levi''s Stadium, San Francisco Bay Area' where stage = 'group' and group_letter = 'J' and ((home_team_id = (select id from public.teams where code='ARG') and away_team_id = (select id from public.teams where code='JOR')) or (home_team_id = (select id from public.teams where code='JOR') and away_team_id = (select id from public.teams where code='ARG')));
update public.matches set kickoff = '2026-06-23T16:00:00Z', venue = 'Arrowhead Stadium, Kansas City' where stage = 'group' and group_letter = 'K' and ((home_team_id = (select id from public.teams where code='COL') and away_team_id = (select id from public.teams where code='COD')) or (home_team_id = (select id from public.teams where code='COD') and away_team_id = (select id from public.teams where code='COL')));
update public.matches set kickoff = '2026-06-23T19:00:00Z', venue = 'NRG Stadium, Houston' where stage = 'group' and group_letter = 'K' and ((home_team_id = (select id from public.teams where code='POR') and away_team_id = (select id from public.teams where code='UZB')) or (home_team_id = (select id from public.teams where code='UZB') and away_team_id = (select id from public.teams where code='POR')));
update public.matches set kickoff = '2026-06-23T20:00:00Z', venue = 'NRG Stadium, Houston' where stage = 'group' and group_letter = 'L' and ((home_team_id = (select id from public.teams where code='ENG') and away_team_id = (select id from public.teams where code='GHA')) or (home_team_id = (select id from public.teams where code='GHA') and away_team_id = (select id from public.teams where code='ENG')));
update public.matches set kickoff = '2026-06-23T23:00:00Z', venue = 'BMO Field, Toronto' where stage = 'group' and group_letter = 'L' and ((home_team_id = (select id from public.teams where code='CRO') and away_team_id = (select id from public.teams where code='PAN')) or (home_team_id = (select id from public.teams where code='PAN') and away_team_id = (select id from public.teams where code='CRO')));
update public.matches set kickoff = '2026-06-24T18:00:00Z', venue = 'Estadio Azteca, Mexico City' where stage = 'group' and group_letter = 'A' and ((home_team_id = (select id from public.teams where code='MEX') and away_team_id = (select id from public.teams where code='KOR')) or (home_team_id = (select id from public.teams where code='KOR') and away_team_id = (select id from public.teams where code='MEX')));
update public.matches set kickoff = '2026-06-24T18:00:00Z', venue = 'Mercedes-Benz Stadium, Atlanta' where stage = 'group' and group_letter = 'A' and ((home_team_id = (select id from public.teams where code='CZE') and away_team_id = (select id from public.teams where code='RSA')) or (home_team_id = (select id from public.teams where code='RSA') and away_team_id = (select id from public.teams where code='CZE')));
update public.matches set kickoff = '2026-06-24T21:00:00Z', venue = 'BC Place, Vancouver' where stage = 'group' and group_letter = 'B' and ((home_team_id = (select id from public.teams where code='CAN') and away_team_id = (select id from public.teams where code='SUI')) or (home_team_id = (select id from public.teams where code='SUI') and away_team_id = (select id from public.teams where code='CAN')));
update public.matches set kickoff = '2026-06-24T21:00:00Z', venue = 'BMO Field, Toronto' where stage = 'group' and group_letter = 'B' and ((home_team_id = (select id from public.teams where code='QAT') and away_team_id = (select id from public.teams where code='BIH')) or (home_team_id = (select id from public.teams where code='BIH') and away_team_id = (select id from public.teams where code='QAT')));
update public.matches set kickoff = '2026-06-25T18:00:00Z', venue = 'MetLife Stadium, New York/NJ' where stage = 'group' and group_letter = 'C' and ((home_team_id = (select id from public.teams where code='BRA') and away_team_id = (select id from public.teams where code='SCO')) or (home_team_id = (select id from public.teams where code='SCO') and away_team_id = (select id from public.teams where code='BRA')));
update public.matches set kickoff = '2026-06-25T18:00:00Z', venue = 'Gillette Stadium, Boston' where stage = 'group' and group_letter = 'C' and ((home_team_id = (select id from public.teams where code='MAR') and away_team_id = (select id from public.teams where code='HAI')) or (home_team_id = (select id from public.teams where code='HAI') and away_team_id = (select id from public.teams where code='MAR')));
update public.matches set kickoff = '2026-06-25T21:00:00Z', venue = 'SoFi Stadium, Los Angeles' where stage = 'group' and group_letter = 'D' and ((home_team_id = (select id from public.teams where code='USA') and away_team_id = (select id from public.teams where code='TUR')) or (home_team_id = (select id from public.teams where code='TUR') and away_team_id = (select id from public.teams where code='USA')));
update public.matches set kickoff = '2026-06-25T21:00:00Z', venue = 'Estadio BBVA, Monterrey' where stage = 'group' and group_letter = 'D' and ((home_team_id = (select id from public.teams where code='PAR') and away_team_id = (select id from public.teams where code='AUS')) or (home_team_id = (select id from public.teams where code='AUS') and away_team_id = (select id from public.teams where code='PAR')));
update public.matches set kickoff = '2026-06-26T16:00:00Z', venue = 'AT&T Stadium, Dallas' where stage = 'group' and group_letter = 'E' and ((home_team_id = (select id from public.teams where code='GER') and away_team_id = (select id from public.teams where code='ECU')) or (home_team_id = (select id from public.teams where code='ECU') and away_team_id = (select id from public.teams where code='GER')));
update public.matches set kickoff = '2026-06-26T16:00:00Z', venue = 'Arrowhead Stadium, Kansas City' where stage = 'group' and group_letter = 'E' and ((home_team_id = (select id from public.teams where code='CIV') and away_team_id = (select id from public.teams where code='CUW')) or (home_team_id = (select id from public.teams where code='CUW') and away_team_id = (select id from public.teams where code='CIV')));
update public.matches set kickoff = '2026-06-26T19:00:00Z', venue = 'NRG Stadium, Houston' where stage = 'group' and group_letter = 'F' and ((home_team_id = (select id from public.teams where code='NED') and away_team_id = (select id from public.teams where code='TUN')) or (home_team_id = (select id from public.teams where code='TUN') and away_team_id = (select id from public.teams where code='NED')));
update public.matches set kickoff = '2026-06-26T19:00:00Z', venue = 'Estadio BBVA, Monterrey' where stage = 'group' and group_letter = 'F' and ((home_team_id = (select id from public.teams where code='JPN') and away_team_id = (select id from public.teams where code='SWE')) or (home_team_id = (select id from public.teams where code='SWE') and away_team_id = (select id from public.teams where code='JPN')));
update public.matches set kickoff = '2026-06-26T22:00:00Z', venue = 'Lumen Field, Seattle' where stage = 'group' and group_letter = 'G' and ((home_team_id = (select id from public.teams where code='BEL') and away_team_id = (select id from public.teams where code='NZL')) or (home_team_id = (select id from public.teams where code='NZL') and away_team_id = (select id from public.teams where code='BEL')));
update public.matches set kickoff = '2026-06-26T22:00:00Z', venue = 'SoFi Stadium, Los Angeles' where stage = 'group' and group_letter = 'G' and ((home_team_id = (select id from public.teams where code='IRN') and away_team_id = (select id from public.teams where code='EGY')) or (home_team_id = (select id from public.teams where code='EGY') and away_team_id = (select id from public.teams where code='IRN')));
update public.matches set kickoff = '2026-06-27T16:00:00Z', venue = 'Mercedes-Benz Stadium, Atlanta' where stage = 'group' and group_letter = 'H' and ((home_team_id = (select id from public.teams where code='ESP') and away_team_id = (select id from public.teams where code='URU')) or (home_team_id = (select id from public.teams where code='URU') and away_team_id = (select id from public.teams where code='ESP')));
update public.matches set kickoff = '2026-06-27T16:00:00Z', venue = 'Hard Rock Stadium, Miami' where stage = 'group' and group_letter = 'H' and ((home_team_id = (select id from public.teams where code='KSA') and away_team_id = (select id from public.teams where code='CPV')) or (home_team_id = (select id from public.teams where code='CPV') and away_team_id = (select id from public.teams where code='KSA')));
update public.matches set kickoff = '2026-06-27T19:00:00Z', venue = 'MetLife Stadium, New York/NJ' where stage = 'group' and group_letter = 'I' and ((home_team_id = (select id from public.teams where code='FRA') and away_team_id = (select id from public.teams where code='NOR')) or (home_team_id = (select id from public.teams where code='NOR') and away_team_id = (select id from public.teams where code='FRA')));
update public.matches set kickoff = '2026-06-27T19:00:00Z', venue = 'Lincoln Financial Field, Philadelphia' where stage = 'group' and group_letter = 'I' and ((home_team_id = (select id from public.teams where code='SEN') and away_team_id = (select id from public.teams where code='IRQ')) or (home_team_id = (select id from public.teams where code='IRQ') and away_team_id = (select id from public.teams where code='SEN')));
update public.matches set kickoff = '2026-06-27T22:00:00Z', venue = 'AT&T Stadium, Dallas' where stage = 'group' and group_letter = 'J' and ((home_team_id = (select id from public.teams where code='ARG') and away_team_id = (select id from public.teams where code='AUT')) or (home_team_id = (select id from public.teams where code='AUT') and away_team_id = (select id from public.teams where code='ARG')));
update public.matches set kickoff = '2026-06-27T22:00:00Z', venue = 'Levi''s Stadium, San Francisco Bay Area' where stage = 'group' and group_letter = 'J' and ((home_team_id = (select id from public.teams where code='ALG') and away_team_id = (select id from public.teams where code='JOR')) or (home_team_id = (select id from public.teams where code='JOR') and away_team_id = (select id from public.teams where code='ALG')));
update public.matches set kickoff = '2026-06-27T21:00:00Z', venue = 'BMO Field, Toronto' where stage = 'group' and group_letter = 'L' and ((home_team_id = (select id from public.teams where code='ENG') and away_team_id = (select id from public.teams where code='PAN')) or (home_team_id = (select id from public.teams where code='PAN') and away_team_id = (select id from public.teams where code='ENG')));
update public.matches set kickoff = '2026-06-27T21:00:00Z', venue = 'AT&T Stadium, Dallas' where stage = 'group' and group_letter = 'L' and ((home_team_id = (select id from public.teams where code='CRO') and away_team_id = (select id from public.teams where code='GHA')) or (home_team_id = (select id from public.teams where code='GHA') and away_team_id = (select id from public.teams where code='CRO')));
update public.matches set kickoff = '2026-06-28T00:00:00Z', venue = 'NRG Stadium, Houston' where stage = 'group' and group_letter = 'K' and ((home_team_id = (select id from public.teams where code='POR') and away_team_id = (select id from public.teams where code='COL')) or (home_team_id = (select id from public.teams where code='COL') and away_team_id = (select id from public.teams where code='POR')));
update public.matches set kickoff = '2026-06-28T00:00:00Z', venue = 'Arrowhead Stadium, Kansas City' where stage = 'group' and group_letter = 'K' and ((home_team_id = (select id from public.teams where code='COD') and away_team_id = (select id from public.teams where code='UZB')) or (home_team_id = (select id from public.teams where code='UZB') and away_team_id = (select id from public.teams where code='COD')));

-- ===== Knockout placeholders =====
update public.matches set kickoff = '2026-06-28T16:00:00Z' where slot = 'R32-1';
update public.matches set kickoff = '2026-06-28T16:00:00Z' where slot = 'R32-2';
update public.matches set kickoff = '2026-06-28T16:00:00Z' where slot = 'R32-3';
update public.matches set kickoff = '2026-06-29T16:00:00Z' where slot = 'R32-4';
update public.matches set kickoff = '2026-06-29T16:00:00Z' where slot = 'R32-5';
update public.matches set kickoff = '2026-06-29T16:00:00Z' where slot = 'R32-6';
update public.matches set kickoff = '2026-06-29T16:00:00Z' where slot = 'R32-7';
update public.matches set kickoff = '2026-06-30T16:00:00Z' where slot = 'R32-8';
update public.matches set kickoff = '2026-06-30T16:00:00Z' where slot = 'R32-9';
update public.matches set kickoff = '2026-06-30T16:00:00Z' where slot = 'R32-10';
update public.matches set kickoff = '2026-07-01T16:00:00Z' where slot = 'R32-11';
update public.matches set kickoff = '2026-07-01T16:00:00Z' where slot = 'R32-12';
update public.matches set kickoff = '2026-07-01T16:00:00Z' where slot = 'R32-13';
update public.matches set kickoff = '2026-07-02T16:00:00Z' where slot = 'R32-14';
update public.matches set kickoff = '2026-07-02T16:00:00Z' where slot = 'R32-15';
update public.matches set kickoff = '2026-07-03T16:00:00Z' where slot = 'R32-16';
update public.matches set kickoff = '2026-07-04T16:00:00Z', venue = 'BC Place, Vancouver' where slot = 'R16-1';
update public.matches set kickoff = '2026-07-04T16:00:00Z', venue = 'Mercedes-Benz Stadium, Atlanta' where slot = 'R16-2';
update public.matches set kickoff = '2026-07-05T16:00:00Z', venue = 'Estadio Azteca, Mexico City' where slot = 'R16-3';
update public.matches set kickoff = '2026-07-05T16:00:00Z', venue = 'MetLife Stadium, New York/NJ' where slot = 'R16-4';
update public.matches set kickoff = '2026-07-06T16:00:00Z', venue = 'Lumen Field, Seattle' where slot = 'R16-5';
update public.matches set kickoff = '2026-07-06T16:00:00Z', venue = 'AT&T Stadium, Dallas' where slot = 'R16-6';
update public.matches set kickoff = '2026-07-07T16:00:00Z', venue = 'NRG Stadium, Houston' where slot = 'R16-7';
update public.matches set kickoff = '2026-07-07T16:00:00Z', venue = 'Lincoln Financial Field, Philadelphia' where slot = 'R16-8';
update public.matches set kickoff = '2026-07-09T16:00:00Z', venue = 'Gillette Stadium, Boston' where slot = 'QF-1';
update public.matches set kickoff = '2026-07-10T16:00:00Z', venue = 'SoFi Stadium, Los Angeles' where slot = 'QF-2';
update public.matches set kickoff = '2026-07-10T16:00:00Z', venue = 'Hard Rock Stadium, Miami' where slot = 'QF-3';
update public.matches set kickoff = '2026-07-11T16:00:00Z', venue = 'Arrowhead Stadium, Kansas City' where slot = 'QF-4';
update public.matches set kickoff = '2026-07-14T16:00:00Z', venue = 'AT&T Stadium, Dallas' where slot = 'SF-1';
update public.matches set kickoff = '2026-07-15T16:00:00Z', venue = 'Mercedes-Benz Stadium, Atlanta' where slot = 'SF-2';
update public.matches set kickoff = '2026-07-18T21:00:00Z', venue = 'Hard Rock Stadium, Miami' where slot = '3P';
update public.matches set kickoff = '2026-07-19T19:00:00Z', venue = 'MetLife Stadium, New York/NJ' where slot = 'F';

commit;

-- Group updates: 72 of 72
-- KO updates:    32 of 32