-- Auto-generated from teams-seed.json. Idempotent: safe to re-run.
-- Run AFTER schema.sql.

-- ===== Teams =====
insert into public.teams (name, code, flag, tier, price, group_letter, confederation, fifa_rank) values
  ('Mexico', 'MEX', '🇲🇽', 'B', 17, 'A', 'CONCACAF', 22),
  ('South Korea', 'KOR', '🇰🇷', 'C', 9, 'A', 'AFC', 21),
  ('Czechia', 'CZE', '🇨🇿', 'C', 9, 'A', 'UEFA', 28),
  ('South Africa', 'RSA', '🇿🇦', 'D', 4, 'A', 'CAF', 39),
  ('Switzerland', 'SUI', '🇨🇭', 'B', 17, 'B', 'UEFA', 17),
  ('Canada', 'CAN', '🇨🇦', 'C', 9, 'B', 'CONCACAF', 27),
  ('Qatar', 'QAT', '🇶🇦', 'D', 4, 'B', 'AFC', 37),
  ('Bosnia & Herzegovina', 'BIH', '🇧🇦', 'C', 9, 'B', 'UEFA', 34),
  ('Brazil', 'BRA', '🇧🇷', 'A', 29, 'C', 'CONMEBOL', 5),
  ('Morocco', 'MAR', '🇲🇦', 'B', 17, 'C', 'CAF', 10),
  ('Scotland', 'SCO', '🏴', 'C', 9, 'C', 'UEFA', 32),
  ('Haiti', 'HAI', '🇭🇹', 'D', 4, 'C', 'CONCACAF', 47),
  ('United States', 'USA', '🇺🇸', 'B', 17, 'D', 'CONCACAF', 19),
  ('Australia', 'AUS', '🇦🇺', 'D', 4, 'D', 'AFC', 24),
  ('Türkiye', 'TUR', '🇹🇷', 'B', 17, 'D', 'UEFA', 26),
  ('Paraguay', 'PAR', '🇵🇾', 'C', 9, 'D', 'CONMEBOL', 36),
  ('Germany', 'GER', '🇩🇪', 'A', 29, 'E', 'UEFA', 8),
  ('Ecuador', 'ECU', '🇪🇨', 'B', 17, 'E', 'CONMEBOL', 16),
  ('Ivory Coast', 'CIV', '🇨🇮', 'C', 9, 'E', 'CAF', 31),
  ('Curaçao', 'CUW', '🇨🇼', 'D', 4, 'E', 'CONCACAF', 48),
  ('Netherlands', 'NED', '🇳🇱', 'A', 29, 'F', 'UEFA', 7),
  ('Japan', 'JPN', '🇯🇵', 'B', 17, 'F', 'AFC', 14),
  ('Sweden', 'SWE', '🇸🇪', 'C', 9, 'F', 'UEFA', 30),
  ('Tunisia', 'TUN', '🇹🇳', 'D', 4, 'F', 'CAF', 33),
  ('Belgium', 'BEL', '🇧🇪', 'A', 29, 'G', 'UEFA', 11),
  ('Iran', 'IRN', '🇮🇷', 'D', 4, 'G', 'AFC', 23),
  ('Egypt', 'EGY', '🇪🇬', 'C', 9, 'G', 'CAF', 20),
  ('New Zealand', 'NZL', '🇳🇿', 'D', 4, 'G', 'OFC', 46),
  ('Spain', 'ESP', '🇪🇸', 'S', 43, 'H', 'UEFA', 2),
  ('Uruguay', 'URU', '🇺🇾', 'B', 17, 'H', 'CONMEBOL', 13),
  ('Saudi Arabia', 'KSA', '🇸🇦', 'D', 4, 'H', 'AFC', 41),
  ('Cape Verde', 'CPV', '🇨🇻', 'D', 4, 'H', 'CAF', 45),
  ('France', 'FRA', '🇫🇷', 'S', 43, 'I', 'UEFA', 3),
  ('Senegal', 'SEN', '🇸🇳', 'C', 9, 'I', 'CAF', 15),
  ('Norway', 'NOR', '🇳🇴', 'B', 17, 'I', 'UEFA', 25),
  ('Iraq', 'IRQ', '🇮🇶', 'D', 4, 'I', 'AFC', 42),
  ('Argentina', 'ARG', '🇦🇷', 'A', 29, 'J', 'CONMEBOL', 1),
  ('Austria', 'AUT', '🇦🇹', 'B', 17, 'J', 'UEFA', 18),
  ('Algeria', 'ALG', '🇩🇿', 'C', 9, 'J', 'CAF', 29),
  ('Jordan', 'JOR', '🇯🇴', 'D', 4, 'J', 'AFC', 43),
  ('Portugal', 'POR', '🇵🇹', 'A', 29, 'K', 'UEFA', 6),
  ('Colombia', 'COL', '🇨🇴', 'B', 17, 'K', 'CONMEBOL', 9),
  ('DR Congo', 'COD', '🇨🇩', 'D', 4, 'K', 'CAF', 35),
  ('Uzbekistan', 'UZB', '🇺🇿', 'D', 4, 'K', 'AFC', 40),
  ('England', 'ENG', '🏴', 'S', 43, 'L', 'UEFA', 4),
  ('Croatia', 'CRO', '🇭🇷', 'B', 17, 'L', 'UEFA', 12),
  ('Panama', 'PAN', '🇵🇦', 'D', 4, 'L', 'CONCACAF', 44),
  ('Ghana', 'GHA', '🇬🇭', 'C', 9, 'L', 'CAF', 38)
on conflict (code) do update set
  name = excluded.name,
  flag = excluded.flag,
  tier = excluded.tier,
  price = excluded.price,
  group_letter = excluded.group_letter,
  confederation = excluded.confederation,
  fifa_rank = excluded.fifa_rank;

-- ===== team_advancement (defaults) =====
insert into public.team_advancement (team_id, result)
select id, 'none' from public.teams
on conflict (team_id) do nothing;

-- ===== Group matches (72) =====
delete from public.matches where stage = 'group' and status = 'scheduled' and home_score is null;

insert into public.matches (stage, group_letter, home_team_id, away_team_id, status) values
  ('group', 'A', (select id from public.teams where code='CZE'), (select id from public.teams where code='KOR'), 'scheduled'),
  ('group', 'A', (select id from public.teams where code='CZE'), (select id from public.teams where code='MEX'), 'scheduled'),
  ('group', 'A', (select id from public.teams where code='CZE'), (select id from public.teams where code='RSA'), 'scheduled'),
  ('group', 'A', (select id from public.teams where code='KOR'), (select id from public.teams where code='MEX'), 'scheduled'),
  ('group', 'A', (select id from public.teams where code='KOR'), (select id from public.teams where code='RSA'), 'scheduled'),
  ('group', 'A', (select id from public.teams where code='MEX'), (select id from public.teams where code='RSA'), 'scheduled'),
  ('group', 'B', (select id from public.teams where code='BIH'), (select id from public.teams where code='CAN'), 'scheduled'),
  ('group', 'B', (select id from public.teams where code='BIH'), (select id from public.teams where code='QAT'), 'scheduled'),
  ('group', 'B', (select id from public.teams where code='BIH'), (select id from public.teams where code='SUI'), 'scheduled'),
  ('group', 'B', (select id from public.teams where code='CAN'), (select id from public.teams where code='QAT'), 'scheduled'),
  ('group', 'B', (select id from public.teams where code='CAN'), (select id from public.teams where code='SUI'), 'scheduled'),
  ('group', 'B', (select id from public.teams where code='QAT'), (select id from public.teams where code='SUI'), 'scheduled'),
  ('group', 'C', (select id from public.teams where code='BRA'), (select id from public.teams where code='HAI'), 'scheduled'),
  ('group', 'C', (select id from public.teams where code='BRA'), (select id from public.teams where code='MAR'), 'scheduled'),
  ('group', 'C', (select id from public.teams where code='BRA'), (select id from public.teams where code='SCO'), 'scheduled'),
  ('group', 'C', (select id from public.teams where code='HAI'), (select id from public.teams where code='MAR'), 'scheduled'),
  ('group', 'C', (select id from public.teams where code='HAI'), (select id from public.teams where code='SCO'), 'scheduled'),
  ('group', 'C', (select id from public.teams where code='MAR'), (select id from public.teams where code='SCO'), 'scheduled'),
  ('group', 'D', (select id from public.teams where code='AUS'), (select id from public.teams where code='PAR'), 'scheduled'),
  ('group', 'D', (select id from public.teams where code='AUS'), (select id from public.teams where code='TUR'), 'scheduled'),
  ('group', 'D', (select id from public.teams where code='AUS'), (select id from public.teams where code='USA'), 'scheduled'),
  ('group', 'D', (select id from public.teams where code='PAR'), (select id from public.teams where code='TUR'), 'scheduled'),
  ('group', 'D', (select id from public.teams where code='PAR'), (select id from public.teams where code='USA'), 'scheduled'),
  ('group', 'D', (select id from public.teams where code='TUR'), (select id from public.teams where code='USA'), 'scheduled'),
  ('group', 'E', (select id from public.teams where code='CIV'), (select id from public.teams where code='CUW'), 'scheduled'),
  ('group', 'E', (select id from public.teams where code='CIV'), (select id from public.teams where code='ECU'), 'scheduled'),
  ('group', 'E', (select id from public.teams where code='CIV'), (select id from public.teams where code='GER'), 'scheduled'),
  ('group', 'E', (select id from public.teams where code='CUW'), (select id from public.teams where code='ECU'), 'scheduled'),
  ('group', 'E', (select id from public.teams where code='CUW'), (select id from public.teams where code='GER'), 'scheduled'),
  ('group', 'E', (select id from public.teams where code='ECU'), (select id from public.teams where code='GER'), 'scheduled'),
  ('group', 'F', (select id from public.teams where code='JPN'), (select id from public.teams where code='NED'), 'scheduled'),
  ('group', 'F', (select id from public.teams where code='JPN'), (select id from public.teams where code='SWE'), 'scheduled'),
  ('group', 'F', (select id from public.teams where code='JPN'), (select id from public.teams where code='TUN'), 'scheduled'),
  ('group', 'F', (select id from public.teams where code='NED'), (select id from public.teams where code='SWE'), 'scheduled'),
  ('group', 'F', (select id from public.teams where code='NED'), (select id from public.teams where code='TUN'), 'scheduled'),
  ('group', 'F', (select id from public.teams where code='SWE'), (select id from public.teams where code='TUN'), 'scheduled'),
  ('group', 'G', (select id from public.teams where code='BEL'), (select id from public.teams where code='EGY'), 'scheduled'),
  ('group', 'G', (select id from public.teams where code='BEL'), (select id from public.teams where code='IRN'), 'scheduled'),
  ('group', 'G', (select id from public.teams where code='BEL'), (select id from public.teams where code='NZL'), 'scheduled'),
  ('group', 'G', (select id from public.teams where code='EGY'), (select id from public.teams where code='IRN'), 'scheduled'),
  ('group', 'G', (select id from public.teams where code='EGY'), (select id from public.teams where code='NZL'), 'scheduled'),
  ('group', 'G', (select id from public.teams where code='IRN'), (select id from public.teams where code='NZL'), 'scheduled'),
  ('group', 'H', (select id from public.teams where code='CPV'), (select id from public.teams where code='ESP'), 'scheduled'),
  ('group', 'H', (select id from public.teams where code='CPV'), (select id from public.teams where code='KSA'), 'scheduled'),
  ('group', 'H', (select id from public.teams where code='CPV'), (select id from public.teams where code='URU'), 'scheduled'),
  ('group', 'H', (select id from public.teams where code='ESP'), (select id from public.teams where code='KSA'), 'scheduled'),
  ('group', 'H', (select id from public.teams where code='ESP'), (select id from public.teams where code='URU'), 'scheduled'),
  ('group', 'H', (select id from public.teams where code='KSA'), (select id from public.teams where code='URU'), 'scheduled'),
  ('group', 'I', (select id from public.teams where code='FRA'), (select id from public.teams where code='IRQ'), 'scheduled'),
  ('group', 'I', (select id from public.teams where code='FRA'), (select id from public.teams where code='NOR'), 'scheduled'),
  ('group', 'I', (select id from public.teams where code='FRA'), (select id from public.teams where code='SEN'), 'scheduled'),
  ('group', 'I', (select id from public.teams where code='IRQ'), (select id from public.teams where code='NOR'), 'scheduled'),
  ('group', 'I', (select id from public.teams where code='IRQ'), (select id from public.teams where code='SEN'), 'scheduled'),
  ('group', 'I', (select id from public.teams where code='NOR'), (select id from public.teams where code='SEN'), 'scheduled'),
  ('group', 'J', (select id from public.teams where code='ALG'), (select id from public.teams where code='ARG'), 'scheduled'),
  ('group', 'J', (select id from public.teams where code='ALG'), (select id from public.teams where code='AUT'), 'scheduled'),
  ('group', 'J', (select id from public.teams where code='ALG'), (select id from public.teams where code='JOR'), 'scheduled'),
  ('group', 'J', (select id from public.teams where code='ARG'), (select id from public.teams where code='AUT'), 'scheduled'),
  ('group', 'J', (select id from public.teams where code='ARG'), (select id from public.teams where code='JOR'), 'scheduled'),
  ('group', 'J', (select id from public.teams where code='AUT'), (select id from public.teams where code='JOR'), 'scheduled'),
  ('group', 'K', (select id from public.teams where code='COD'), (select id from public.teams where code='COL'), 'scheduled'),
  ('group', 'K', (select id from public.teams where code='COD'), (select id from public.teams where code='POR'), 'scheduled'),
  ('group', 'K', (select id from public.teams where code='COD'), (select id from public.teams where code='UZB'), 'scheduled'),
  ('group', 'K', (select id from public.teams where code='COL'), (select id from public.teams where code='POR'), 'scheduled'),
  ('group', 'K', (select id from public.teams where code='COL'), (select id from public.teams where code='UZB'), 'scheduled'),
  ('group', 'K', (select id from public.teams where code='POR'), (select id from public.teams where code='UZB'), 'scheduled'),
  ('group', 'L', (select id from public.teams where code='CRO'), (select id from public.teams where code='ENG'), 'scheduled'),
  ('group', 'L', (select id from public.teams where code='CRO'), (select id from public.teams where code='GHA'), 'scheduled'),
  ('group', 'L', (select id from public.teams where code='CRO'), (select id from public.teams where code='PAN'), 'scheduled'),
  ('group', 'L', (select id from public.teams where code='ENG'), (select id from public.teams where code='GHA'), 'scheduled'),
  ('group', 'L', (select id from public.teams where code='ENG'), (select id from public.teams where code='PAN'), 'scheduled'),
  ('group', 'L', (select id from public.teams where code='GHA'), (select id from public.teams where code='PAN'), 'scheduled');

-- ===== Knockout placeholders (32) =====
delete from public.matches where stage <> 'group' and status = 'scheduled' and home_team_id is null and away_team_id is null;

insert into public.matches (stage, slot, status) values
  ('R32', 'R32-1', 'scheduled'),
  ('R32', 'R32-2', 'scheduled'),
  ('R32', 'R32-3', 'scheduled'),
  ('R32', 'R32-4', 'scheduled'),
  ('R32', 'R32-5', 'scheduled'),
  ('R32', 'R32-6', 'scheduled'),
  ('R32', 'R32-7', 'scheduled'),
  ('R32', 'R32-8', 'scheduled'),
  ('R32', 'R32-9', 'scheduled'),
  ('R32', 'R32-10', 'scheduled'),
  ('R32', 'R32-11', 'scheduled'),
  ('R32', 'R32-12', 'scheduled'),
  ('R32', 'R32-13', 'scheduled'),
  ('R32', 'R32-14', 'scheduled'),
  ('R32', 'R32-15', 'scheduled'),
  ('R32', 'R32-16', 'scheduled'),
  ('R16', 'R16-1', 'scheduled'),
  ('R16', 'R16-2', 'scheduled'),
  ('R16', 'R16-3', 'scheduled'),
  ('R16', 'R16-4', 'scheduled'),
  ('R16', 'R16-5', 'scheduled'),
  ('R16', 'R16-6', 'scheduled'),
  ('R16', 'R16-7', 'scheduled'),
  ('R16', 'R16-8', 'scheduled'),
  ('QF', 'QF-1', 'scheduled'),
  ('QF', 'QF-2', 'scheduled'),
  ('QF', 'QF-3', 'scheduled'),
  ('QF', 'QF-4', 'scheduled'),
  ('SF', 'SF-1', 'scheduled'),
  ('SF', 'SF-2', 'scheduled'),
  ('3P', '3P', 'scheduled'),
  ('F', 'F', 'scheduled');
