-- Re-tier teams per the v3 tier assignment. Idempotent.
-- Pricing unchanged from rulebook v2: S=43, A=29, B=17, C=9, D=4.

begin;
update public.teams set tier = 'S', price = 43 where code = 'ESP';
update public.teams set tier = 'S', price = 43 where code = 'FRA';
update public.teams set tier = 'S', price = 43 where code = 'ENG';
update public.teams set tier = 'A', price = 29 where code = 'POR';
update public.teams set tier = 'A', price = 29 where code = 'BRA';
update public.teams set tier = 'A', price = 29 where code = 'ARG';
update public.teams set tier = 'A', price = 29 where code = 'GER';
update public.teams set tier = 'A', price = 29 where code = 'NED';
update public.teams set tier = 'A', price = 29 where code = 'BEL';
update public.teams set tier = 'B', price = 17 where code = 'NOR';
update public.teams set tier = 'B', price = 17 where code = 'COL';
update public.teams set tier = 'B', price = 17 where code = 'JPN';
update public.teams set tier = 'B', price = 17 where code = 'MAR';
update public.teams set tier = 'B', price = 17 where code = 'MEX';
update public.teams set tier = 'B', price = 17 where code = 'USA';
update public.teams set tier = 'B', price = 17 where code = 'URU';
update public.teams set tier = 'B', price = 17 where code = 'CRO';
update public.teams set tier = 'B', price = 17 where code = 'SUI';
update public.teams set tier = 'B', price = 17 where code = 'TUR';
update public.teams set tier = 'B', price = 17 where code = 'ECU';
update public.teams set tier = 'B', price = 17 where code = 'AUT';
update public.teams set tier = 'C', price = 9 where code = 'CIV';
update public.teams set tier = 'C', price = 9 where code = 'SWE';
update public.teams set tier = 'C', price = 9 where code = 'CAN';
update public.teams set tier = 'C', price = 9 where code = 'SEN';
update public.teams set tier = 'C', price = 9 where code = 'SCO';
update public.teams set tier = 'C', price = 9 where code = 'PAR';
update public.teams set tier = 'C', price = 9 where code = 'ALG';
update public.teams set tier = 'C', price = 9 where code = 'EGY';
update public.teams set tier = 'C', price = 9 where code = 'CZE';
update public.teams set tier = 'C', price = 9 where code = 'GHA';
update public.teams set tier = 'C', price = 9 where code = 'BIH';
update public.teams set tier = 'C', price = 9 where code = 'KOR';
update public.teams set tier = 'D', price = 4 where code = 'IRN';
update public.teams set tier = 'D', price = 4 where code = 'TUN';
update public.teams set tier = 'D', price = 4 where code = 'AUS';
update public.teams set tier = 'D', price = 4 where code = 'COD';
update public.teams set tier = 'D', price = 4 where code = 'CPV';
update public.teams set tier = 'D', price = 4 where code = 'UZB';
update public.teams set tier = 'D', price = 4 where code = 'PAN';
update public.teams set tier = 'D', price = 4 where code = 'HAI';
update public.teams set tier = 'D', price = 4 where code = 'CUW';
update public.teams set tier = 'D', price = 4 where code = 'IRQ';
update public.teams set tier = 'D', price = 4 where code = 'JOR';
update public.teams set tier = 'D', price = 4 where code = 'QAT';
update public.teams set tier = 'D', price = 4 where code = 'KSA';
update public.teams set tier = 'D', price = 4 where code = 'NZL';
update public.teams set tier = 'D', price = 4 where code = 'RSA';
commit;
